import { ObjectId } from 'mongodb';
import type { JobListing } from './type.js';
import { getDb, closeDb } from '../../../db.js';

async function seed() {
  const db = await getDb('queries');
  const JobListings = db.collection<JobListing>('JobListings');

  const dummyJobs: JobListing[] = [
    {
      _id: new ObjectId(),
      title: 'Frontend Developer',
      company: 'TechNova',
      location: 'Bangalore, India',
      remote: true,
      salary: { min: 600000, max: 1200000 },
      skills: ['React', 'TypeScript', 'CSS', 'HTML'],
      postedAt: new Date('2026-03-01'),
    },
    {
      _id: new ObjectId(),
      title: 'Backend Developer',
      company: 'DataForge',
      location: 'Hyderabad, India',
      remote: false,
      salary: { min: 700000, max: 1400000 },
      skills: ['Node.js', 'Express', 'MongoDB', 'Docker'],
      postedAt: new Date('2026-03-02'),
    },
    {
      _id: new ObjectId(),
      title: 'Full Stack Developer',
      company: 'CloudWave',
      location: 'Pune, India',
      remote: true,
      salary: { min: 800000, max: 1500000 },
      skills: ['React', 'Node.js', 'PostgreSQL', 'AWS'],
      postedAt: new Date('2026-03-03'),
    },
    {
      _id: new ObjectId(),
      title: 'DevOps Engineer',
      company: 'InfraScale',
      location: 'Chennai, India',
      remote: false,
      salary: { min: 900000, max: 1700000 },
      skills: ['Docker', 'Kubernetes', 'AWS', 'CI/CD'],
      postedAt: new Date('2026-03-04'),
    },
    {
      _id: new ObjectId(),
      title: 'Data Scientist',
      company: 'InsightLabs',
      location: 'Delhi, India',
      remote: true,
      salary: { min: 1000000, max: 2000000 },
      skills: ['Python', 'TensorFlow', 'Pandas', 'Machine Learning'],
      postedAt: new Date('2026-03-05'),
    },
    {
      _id: new ObjectId(),
      title: 'Mobile App Developer',
      company: 'AppSprint',
      location: 'Mumbai, India',
      remote: false,
      salary: { min: 700000, max: 1300000 },
      skills: ['Flutter', 'Dart', 'Firebase'],
      postedAt: new Date('2026-03-06'),
    },
    {
      _id: new ObjectId(),
      title: 'Android Developer',
      company: 'MobilitySoft',
      location: 'Noida, India',
      remote: true,
      salary: { min: 600000, max: 1100000 },
      skills: ['Kotlin', 'Android SDK', 'REST APIs'],
      postedAt: new Date('2026-03-07'),
    },
    {
      _id: new ObjectId(),
      title: 'iOS Developer',
      company: 'SwiftTech',
      location: 'Gurgaon, India',
      remote: false,
      salary: { min: 750000, max: 1350000 },
      skills: ['Swift', 'UIKit', 'Xcode'],
      postedAt: new Date('2026-03-08'),
    },
    {
      _id: new ObjectId(),
      title: 'QA Engineer',
      company: 'QualityWorks',
      location: 'Kolkata, India',
      remote: true,
      salary: { min: 500000, max: 900000 },
      skills: ['Selenium', 'Cypress', 'Automation Testing'],
      postedAt: new Date('2026-03-09'),
    },
    {
      _id: new ObjectId(),
      title: 'Cybersecurity Analyst',
      company: 'SecureNet',
      location: 'Bangalore, India',
      remote: false,
      salary: { min: 900000, max: 1800000 },
      skills: ['Network Security', 'SIEM', 'Penetration Testing'],
      postedAt: new Date('2026-03-10'),
    },
    {
      _id: new ObjectId(),
      title: 'Machine Learning Engineer',
      company: 'AIForge',
      location: 'Hyderabad, India',
      remote: true,
      salary: { min: 1100000, max: 2200000 },
      skills: ['Python', 'PyTorch', 'Deep Learning'],
      postedAt: new Date('2026-03-11'),
    },
    {
      _id: new ObjectId(),
      title: 'Cloud Engineer',
      company: 'SkyCompute',
      location: 'Pune, India',
      remote: false,
      salary: { min: 950000, max: 1750000 },
      skills: ['AWS', 'Terraform', 'Kubernetes'],
      postedAt: new Date('2026-03-12'),
    },
    {
      _id: new ObjectId(),
      title: 'UI/UX Designer',
      company: 'DesignFlow',
      location: 'Mumbai, India',
      remote: true,
      salary: { min: 600000, max: 1000000 },
      skills: ['Figma', 'User Research', 'Prototyping'],
      postedAt: new Date('2026-03-13'),
    },
    {
      _id: new ObjectId(),
      title: 'Product Manager',
      company: 'VisionaryTech',
      location: 'Delhi, India',
      remote: false,
      salary: { min: 1200000, max: 2400000 },
      skills: ['Product Strategy', 'Agile', 'Roadmapping'],
      postedAt: new Date('2026-03-14'),
    },
    {
      _id: new ObjectId(),
      title: 'Blockchain Developer',
      company: 'ChainCore',
      location: 'Bangalore, India',
      remote: true,
      salary: { min: 1000000, max: 2100000 },
      skills: ['Solidity', 'Ethereum', 'Web3.js'],
      postedAt: new Date('2026-03-15'),
    },
    {
      _id: new ObjectId(),
      title: 'Game Developer',
      company: 'PixelForge',
      location: 'Hyderabad, India',
      remote: false,
      salary: { min: 700000, max: 1400000 },
      skills: ['Unity', 'C#', 'Game Physics'],
      postedAt: new Date('2026-03-16'),
    },
    {
      _id: new ObjectId(),
      title: 'Site Reliability Engineer',
      company: 'ReliantOps',
      location: 'Chennai, India',
      remote: true,
      salary: { min: 1000000, max: 1900000 },
      skills: ['Linux', 'Kubernetes', 'Monitoring'],
      postedAt: new Date('2026-03-17'),
    },
    {
      _id: new ObjectId(),
      title: 'Data Engineer',
      company: 'PipelineTech',
      location: 'Pune, India',
      remote: false,
      salary: { min: 900000, max: 1700000 },
      skills: ['Apache Spark', 'Kafka', 'Python'],
      postedAt: new Date('2026-03-18'),
    },
    {
      _id: new ObjectId(),
      title: 'Technical Support Engineer',
      company: 'HelpDeskPro',
      location: 'Noida, India',
      remote: true,
      salary: { min: 400000, max: 800000 },
      skills: ['Troubleshooting', 'Networking', 'Customer Support'],
      postedAt: new Date('2026-03-19'),
    },
    {
      _id: new ObjectId(),
      title: 'AI Research Engineer',
      company: 'FutureAI',
      location: 'Bangalore, India',
      remote: true,
      salary: { min: 1300000, max: 2500000 },
      skills: ['Python', 'Transformers', 'Research'],
      postedAt: new Date('2026-03-20'),
    },
  ];

  await JobListings.deleteMany({});
  await JobListings.insertMany(dummyJobs);
  console.log('Job listings seeded!');
  await closeDb();
}

seed();
